# Generated by Django 4.1.7 on 2023-04-12 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0008_alter_recomment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recomment',
            old_name='content',
            new_name='recontent',
        ),
    ]
