# Generated by Django 4.2 on 2023-04-10 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Todo',
        ),
    ]
