# Generated by Django 4.2 on 2023-04-10 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0004_alter_todo_deadline_dt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['deadline_dt']},
        ),
    ]
