# Generated by Django 4.2 on 2023-04-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0005_alter_todo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline_dt',
            field=models.DateTimeField(),
        ),
    ]
